-- =============================================================================
-- 000010 — Support functions
--
-- Segment execution, atomic customer enrolment, referral qualification and
-- gift-card redemption. Each replaces a read-modify-write sequence that used to
-- live in application code and was not safe under concurrency.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Segment execution
--
-- `p_predicate` is generated by lib/segments/compile.ts from an allow-list of
-- columns and operators; all merchant-supplied values arrive separately in
-- `p_params` as JSON and are referenced by index, never interpolated. The
-- function is the only place that runs dynamic SQL, and it hard-scopes every
-- query to a single business_id.
-- -----------------------------------------------------------------------------

create or replace function fidelio_segment_count(
  p_business_id uuid,
  p_predicate text,
  p_params jsonb default '[]'::jsonb
)
returns int
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_count int;
begin
  execute format(
    'select count(*) from customers c
      where c.business_id = %L
        and c.status = ''active''
        and c.merged_into_customer_id is null
        and (%s)',
    p_business_id,
    coalesce(nullif(trim(p_predicate), ''), 'true')
  )
  into v_count
  using p_params;
  return coalesce(v_count, 0);
end;
$$;

create or replace function fidelio_segment_customers(
  p_business_id uuid,
  p_predicate text,
  p_params jsonb default '[]'::jsonb,
  p_limit int default 500,
  p_offset int default 0
)
returns setof customers
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  return query execute format(
    'select c.* from customers c
      where c.business_id = %L
        and c.status = ''active''
        and c.merged_into_customer_id is null
        and (%s)
      order by c.created_at desc
      limit %s offset %s',
    p_business_id,
    coalesce(nullif(trim(p_predicate), ''), 'true'),
    greatest(1, least(p_limit, 5000)),
    greatest(0, p_offset)
  )
  using p_params;
end;
$$;

-- Ids only — used by campaign fan-out where the full row is wasteful.
create or replace function fidelio_segment_customer_ids(
  p_business_id uuid,
  p_predicate text,
  p_params jsonb default '[]'::jsonb,
  p_limit int default 5000,
  p_offset int default 0
)
returns table (id uuid)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  return query execute format(
    'select c.id from customers c
      where c.business_id = %L
        and c.status = ''active''
        and c.merged_into_customer_id is null
        and (%s)
      order by c.id
      limit %s offset %s',
    p_business_id,
    coalesce(nullif(trim(p_predicate), ''), 'true'),
    greatest(1, least(p_limit, 20000)),
    greatest(0, p_offset)
  )
  using p_params;
end;
$$;

-- Single-customer membership test. Automations need "does this person still
-- match?" without materialising the whole audience.
create or replace function fidelio_segment_matches(
  p_business_id uuid,
  p_customer_id uuid,
  p_predicate text,
  p_params jsonb default '[]'::jsonb
)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_match boolean;
begin
  execute format(
    'select exists (
       select 1 from customers c
        where c.business_id = %L
          and c.id = %L
          and c.status = ''active''
          and c.merged_into_customer_id is null
          and (%s))',
    p_business_id,
    p_customer_id,
    coalesce(nullif(trim(p_predicate), ''), 'true')
  )
  into v_match
  using p_params;
  return coalesce(v_match, false);
end;
$$;

-- -----------------------------------------------------------------------------
-- Rule usage counter
-- -----------------------------------------------------------------------------

create or replace function fidelio_increment_rule_usage(p_rule_id uuid)
returns void
language sql
security definer
set search_path = public
as $$
  update earning_rules set usage_count = usage_count + 1 where id = p_rule_id;
$$;

-- -----------------------------------------------------------------------------
-- Customer enrolment
--
-- Replaces a select-then-insert in application code that raced two people
-- scanning the same QR code at once and could create duplicate accounts or
-- award a referral bonus twice.
-- -----------------------------------------------------------------------------

create or replace function fidelio_enroll_customer(
  p_business_id uuid,
  p_email citext,
  p_name text default null,
  p_first_name text default null,
  p_last_name text default null,
  p_phone text default null,
  p_birthday date default null,
  p_locale text default null,
  p_source text default 'qr',
  p_location_id uuid default null,
  p_referral_code text default null,
  p_consents jsonb default '{}'::jsonb,
  p_consent_ip inet default null,
  p_custom_fields jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_customer customers;
  v_is_new boolean := false;
  v_referrer customers;
  v_referral_id uuid;
begin
  insert into customers (
    business_id, email, name, first_name, last_name, phone, birthday, locale,
    source, signup_location_id, custom_fields,
    consent_email, consent_sms, consent_whatsapp, consent_push, consent_marketing,
    consent_updated_at, consent_source, consent_ip, terms_accepted_at
  ) values (
    p_business_id, p_email, p_name, p_first_name, p_last_name, p_phone, p_birthday, p_locale,
    p_source, p_location_id, coalesce(p_custom_fields, '{}'::jsonb),
    coalesce((p_consents ->> 'email')::boolean, true),
    coalesce((p_consents ->> 'sms')::boolean, false),
    coalesce((p_consents ->> 'whatsapp')::boolean, false),
    coalesce((p_consents ->> 'push')::boolean, true),
    coalesce((p_consents ->> 'marketing')::boolean, false),
    now(), p_source, p_consent_ip, now()
  )
  on conflict (business_id, email) do update
    set name = coalesce(customers.name, excluded.name),
        first_name = coalesce(customers.first_name, excluded.first_name),
        last_name = coalesce(customers.last_name, excluded.last_name),
        phone = coalesce(customers.phone, excluded.phone),
        birthday = coalesce(customers.birthday, excluded.birthday),
        locale = coalesce(customers.locale, excluded.locale),
        updated_at = now()
  returning * into v_customer;

  -- xmax = 0 identifies a freshly inserted row rather than an updated one.
  select (xmax = 0) into v_is_new
    from customers where id = v_customer.id;

  if v_is_new then
    insert into activity_events (business_id, customer_id, location_id, type, source)
    values (p_business_id, v_customer.id, p_location_id, 'signup', p_source);

    -- Referral: recorded as pending. The bonus is only paid once the friend
    -- actually transacts, which is what closes the self-referral loophole.
    if p_referral_code is not null and length(trim(p_referral_code)) > 0 then
      select * into v_referrer
        from customers
       where business_id = p_business_id
         and upper(referral_code) = upper(trim(p_referral_code))
         and id <> v_customer.id
         and status = 'active';

      if found and v_referrer.email <> p_email then
        insert into referrals (
          business_id, referrer_customer_id, referred_customer_id,
          referred_email, code, status
        ) values (
          p_business_id, v_referrer.id, v_customer.id, p_email,
          upper(trim(p_referral_code)), 'pending'
        )
        on conflict do nothing
        returning id into v_referral_id;

        update customers set referred_by = v_referrer.id where id = v_customer.id;
      end if;
    end if;
  end if;

  -- Make sure an account exists for every active program so the wallet card
  -- and the dashboard have something to render immediately.
  perform fidelio_ensure_account(p_business_id, p.id, v_customer.id)
    from loyalty_programs p
   where p.business_id = p_business_id and p.is_active;

  select * into v_customer from customers where id = v_customer.id;

  return jsonb_build_object(
    'is_new', v_is_new,
    'customer_id', v_customer.id,
    'referral_id', v_referral_id,
    'referral_code', v_customer.referral_code
  );
end;
$$;

-- -----------------------------------------------------------------------------
-- Referral qualification — pays out only after real activity
-- -----------------------------------------------------------------------------

create or replace function fidelio_qualify_referrals(p_business_id uuid, p_customer_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_referral referrals;
  v_program loyalty_programs;
  v_rule earning_rules;
  v_referrer_award numeric := 0;
  v_referred_award numeric := 0;
  v_referrer_entry jsonb;
  v_referred_entry jsonb;
begin
  select * into v_referral
    from referrals
   where business_id = p_business_id
     and referred_customer_id = p_customer_id
     and status = 'pending'
   for update;

  if not found then
    return jsonb_build_object('qualified', false);
  end if;

  update referrals
     set qualifying_event_count = qualifying_event_count + 1
   where id = v_referral.id
  returning * into v_referral;

  if v_referral.qualifying_event_count < v_referral.qualifies_after_events then
    return jsonb_build_object('qualified', false, 'progress', v_referral.qualifying_event_count);
  end if;

  select * into v_program
    from loyalty_programs
   where business_id = p_business_id and is_default and is_active
   limit 1;

  if not found then
    update referrals set status = 'qualified', qualified_at = now() where id = v_referral.id;
    return jsonb_build_object('qualified', true, 'rewarded', false);
  end if;

  select * into v_rule
    from earning_rules
   where program_id = v_program.id and trigger = 'referral' and is_active
   order by priority limit 1;
  v_referrer_award := coalesce(v_rule.award_amount, 1);

  select * into v_rule
    from earning_rules
   where program_id = v_program.id and trigger = 'referred_signup' and is_active
   order by priority limit 1;
  v_referred_award := coalesce(v_rule.award_amount, 0);

  if v_referrer_award > 0 then
    v_referrer_entry := fidelio_credit_account(
      p_business_id, v_program.id, v_referral.referrer_customer_id, v_referrer_award,
      'earn', 'Referral bonus', null, null, null, null, null,
      'referral:' || v_referral.id::text || ':referrer'
    );
  end if;

  if v_referred_award > 0 then
    v_referred_entry := fidelio_credit_account(
      p_business_id, v_program.id, p_customer_id, v_referred_award,
      'earn', 'Welcome referral bonus', null, null, null, null, null,
      'referral:' || v_referral.id::text || ':referred'
    );
  end if;

  update referrals
     set status = 'rewarded',
         qualified_at = coalesce(qualified_at, now()),
         rewarded_at = now(),
         referrer_ledger_entry_id = nullif(v_referrer_entry ->> 'entry_id', '')::uuid,
         referred_ledger_entry_id = nullif(v_referred_entry ->> 'entry_id', '')::uuid
   where id = v_referral.id;

  insert into activity_events (business_id, customer_id, type, source, metadata)
  values (
    p_business_id, v_referral.referrer_customer_id, 'referral', 'app',
    jsonb_build_object('referral_id', v_referral.id, 'award', v_referrer_award)
  );

  return jsonb_build_object(
    'qualified', true,
    'rewarded', true,
    'referral_id', v_referral.id,
    'referrer_customer_id', v_referral.referrer_customer_id,
    'referrer_award', v_referrer_award,
    'referred_award', v_referred_award
  );
end;
$$;

-- -----------------------------------------------------------------------------
-- Gift cards — atomic partial redemption
-- -----------------------------------------------------------------------------

create or replace function fidelio_redeem_gift_card(
  p_business_id uuid,
  p_code text,
  p_amount numeric default null,
  p_location_id uuid default null,
  p_staff_user_id uuid default null,
  p_idempotency_key text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_card gift_cards;
  v_spend numeric;
  v_new_remaining numeric;
  v_existing gift_card_transactions;
begin
  if p_idempotency_key is not null then
    select * into v_existing
      from gift_card_transactions
     where business_id = p_business_id and idempotency_key = p_idempotency_key;
    if found then
      return jsonb_build_object(
        'duplicate', true,
        'redeemed_amount', -v_existing.amount,
        'remaining_value', v_existing.balance_after
      );
    end if;
  end if;

  select * into v_card
    from gift_cards
   where business_id = p_business_id and upper(code) = upper(trim(p_code))
   for update;

  if not found then
    raise exception 'Invalid gift card code' using errcode = 'no_data_found';
  end if;
  if v_card.status <> 'active' then
    raise exception 'Gift card is %', v_card.status
      using errcode = 'check_violation', hint = 'gift_card_inactive';
  end if;
  if v_card.expires_at is not null and v_card.expires_at < now() then
    update gift_cards set status = 'expired' where id = v_card.id;
    raise exception 'Gift card has expired'
      using errcode = 'check_violation', hint = 'gift_card_expired';
  end if;
  if v_card.remaining_value <= 0 then
    raise exception 'Gift card has no remaining value'
      using errcode = 'check_violation', hint = 'gift_card_empty';
  end if;

  v_spend := least(coalesce(p_amount, v_card.remaining_value), v_card.remaining_value);
  if v_spend <= 0 then
    raise exception 'Redemption amount must be positive' using errcode = 'check_violation';
  end if;

  v_new_remaining := v_card.remaining_value - v_spend;

  update gift_cards
     set remaining_value = v_new_remaining,
         status = case when v_new_remaining <= 0 then 'depleted' else status end,
         redeemed_at = case when v_new_remaining <= 0 then now() else redeemed_at end
   where id = v_card.id;

  insert into gift_card_transactions (
    business_id, gift_card_id, amount, balance_after, kind,
    location_id, staff_user_id, idempotency_key
  ) values (
    p_business_id, v_card.id, -v_spend, v_new_remaining, 'redeem',
    p_location_id, p_staff_user_id, p_idempotency_key
  );

  if v_card.recipient_customer_id is not null then
    insert into activity_events (
      business_id, customer_id, location_id, type, amount, source, staff_user_id, metadata
    ) values (
      p_business_id, v_card.recipient_customer_id, p_location_id, 'gift_card', v_spend,
      'pos', p_staff_user_id, jsonb_build_object('gift_card_id', v_card.id)
    );
  end if;

  return jsonb_build_object(
    'duplicate', false,
    'gift_card_id', v_card.id,
    'redeemed_amount', v_spend,
    'remaining_value', v_new_remaining
  );
end;
$$;

-- -----------------------------------------------------------------------------
-- Counters — atomic increments so concurrent sends do not lose updates
-- -----------------------------------------------------------------------------

create or replace function fidelio_increment_campaign_counter(
  p_campaign_id uuid,
  p_column text,
  p_by int default 1
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Allow-list the column name: it is the only identifier interpolated here.
  if p_column not in (
    'sent_count', 'failed_count', 'delivered_count',
    'opened_count', 'clicked_count', 'unsubscribed_count', 'reach_count'
  ) then
    raise exception 'Unsupported campaign counter %', p_column using errcode = 'check_violation';
  end if;

  execute format('update campaigns set %I = %I + $1 where id = $2', p_column, p_column)
    using p_by, p_campaign_id;
end;
$$;

create or replace function fidelio_increment_automation_completed(p_automation_id uuid)
returns void
language sql
security definer
set search_path = public
as $$
  update automations set completed_count = completed_count + 1 where id = p_automation_id;
$$;

-- Month/day match without a function-wrapped column scan, backed by the
-- expression index created in 000003.
create or replace function fidelio_customers_with_date_today(
  p_business_id uuid,
  p_column text,
  p_month int,
  p_day int
)
returns table (id uuid)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if p_column not in ('birthday', 'anniversary') then
    raise exception 'Unsupported date column %', p_column using errcode = 'check_violation';
  end if;

  return query execute format(
    'select c.id from customers c
      where c.business_id = $1
        and c.status = ''active''
        and c.%I is not null
        and extract(month from c.%I) = $2
        and extract(day from c.%I) = $3
      limit 5000',
    p_column, p_column, p_column
  )
  using p_business_id, p_month, p_day;
end;
$$;

-- -----------------------------------------------------------------------------
-- Automation enrolment guard — cooldown enforced in one atomic check
-- -----------------------------------------------------------------------------

create or replace function fidelio_enroll_automation(
  p_business_id uuid,
  p_automation_id uuid,
  p_customer_id uuid,
  p_scheduled_for timestamptz,
  p_event_id uuid default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_automation automations;
  v_run_id uuid;
begin
  select * into v_automation from automations where id = p_automation_id and is_active;
  if not found then return null; end if;

  -- Respect the cooldown: never re-enrol someone we contacted recently.
  if exists (
    select 1 from automation_runs
     where automation_id = p_automation_id
       and customer_id = p_customer_id
       and status in ('scheduled', 'running', 'completed')
       and created_at > now() - make_interval(days => v_automation.cooldown_days)
  ) then
    return null;
  end if;

  insert into automation_runs (
    business_id, automation_id, customer_id, scheduled_for, trigger_event_id
  ) values (
    p_business_id, p_automation_id, p_customer_id, p_scheduled_for, p_event_id
  )
  returning id into v_run_id;

  update automations set enrolled_count = enrolled_count + 1 where id = p_automation_id;

  return v_run_id;
end;
$$;
