'use client'

import * as React from 'react'
import { MapPin, Sparkles } from 'lucide-react'
import { cn } from '@/lib/utils'
import { useI18n } from '@/lib/i18n'
import {
  cardBackground,
  fontStack,
  shift,
  type ResolvedCardDesign,
} from '@/lib/wallet/card-design'

/**
 * The loyalty card, as each wallet actually lays it out.
 *
 * Two renderers rather than one with a badge, because Apple and Google are not
 * the same product wearing different colours and a merchant deciding what their
 * customer will hold deserves to see the real difference:
 *
 *   * **Apple** paints the whole pass in the brand colour. Fields are stacked in
 *     labelled rows — header, primary, secondary, auxiliary — and the barcode
 *     sits in a white well at the bottom with the serial beneath it.
 *   * **Google** paints a brand-coloured *header* on a neutral surface. The
 *     balance is a large module, the logo is a circle, and the barcode is a wide
 *     white panel. The chrome around it is Google's, not the merchant's.
 *
 * Both consume `ResolvedCardDesign` — the same structure the pass builder uses —
 * so the preview cannot drift from what is generated. That was the whole reason
 * to resolve the design in an isomorphic module.
 *
 * These are previews, and the UI says so next to them. They are not generated by
 * Apple's or Google's SDK and must never be presented as though they were.
 */

export type CardPreviewData = {
  organizationName: string
  programName: string
  memberName: string | null
  memberSince: string | null
  tierName: string | null
  locationName: string | null
  balance: number
  goal: number | null
  unitSingular: string
  unitPlural: string
  rewardName: string | null
  /**
   * What the merchant's brand kit puts on the reverse.
   *
   * Optional because the landing page has no merchant. When present the back
   * shows exactly what a real pass carries there — both wallets render contact
   * details and small print on the reverse, and it is the only place the brand
   * kit's phone number, address and social handles reach a customer at all.
   */
  contact?: {
    description?: string | null
    website?: string | null
    phone?: string | null
    email?: string | null
    address?: string | null
    socials?: { instagram?: string | null; facebook?: string | null; tiktok?: string | null }
  }
}

export type CardPreviewProps = {
  platform: 'apple' | 'google'
  design: ResolvedCardDesign
  data: CardPreviewData
  /** Shows the reverse of the card — custom message, terms, contact. */
  showBack?: boolean
  /** Bumped on change so the balance can animate. */
  animateKey?: number
  className?: string
}

export function CardPreview({ platform, ...rest }: CardPreviewProps) {
  return platform === 'apple' ? <ApplePassPreview {...rest} /> : <GooglePassPreview {...rest} />
}

// -----------------------------------------------------------------------------
// Shared pieces
// -----------------------------------------------------------------------------

function useProgress(data: CardPreviewData) {
  const rewardReady = data.goal != null && data.goal > 0 && data.balance >= data.goal
  const remaining = data.goal != null ? Math.max(0, data.goal - data.balance) : null
  const ratio = data.goal && data.goal > 0 ? Math.min(1, data.balance / data.goal) : 0
  return { rewardReady, remaining, ratio }
}

/** Initials for the logo well when the merchant has not uploaded a logo yet. */
function initials(name: string): string {
  const words = name.trim().split(/\s+/).filter(Boolean)
  if (words.length === 0) return '?'
  if (words.length === 1) return words[0]!.slice(0, 2).toUpperCase()
  return `${words[0]![0]}${words[1]![0]}`.toUpperCase()
}

function LogoMark({
  design,
  name,
  className,
  style,
}: {
  design: ResolvedCardDesign
  name: string
  className?: string
  style?: React.CSSProperties
}) {
  if (design.logoUrl) {
    return (
      // A merchant's logo is arbitrary user content, so it is contained rather
      // than cropped — a wordmark cropped to a square is a broken brand.
      // eslint-disable-next-line @next/next/no-img-element
      <img
        src={design.logoUrl}
        alt=""
        className={cn('object-contain', className)}
        style={style}
        loading="lazy"
        decoding="async"
      />
    )
  }
  return (
    <span aria-hidden className={cn('flex items-center justify-center font-bold', className)} style={style}>
      {initials(name)}
    </span>
  )
}

/**
 * The hero/strip image.
 *
 * Apple embeds this as `strip.png` and Google as `heroImage`, and both were
 * already consuming `design.heroImageUrl` — but nothing rendered it, so a
 * merchant had no way to see what they were shipping. Rendered as a band because
 * that is where both platforms place it: full width, fixed aspect, cropped.
 *
 * `<img>` rather than `next/image` deliberately: the source is a merchant URL on
 * an arbitrary host, and the optimiser is disabled for this deployment anyway.
 */
function HeroStrip({ url, className }: { url: string; className?: string }) {
  return (
    /* eslint-disable-next-line @next/next/no-img-element */
    <img
      src={url}
      alt=""
      aria-hidden
      className={cn('h-16 w-full object-cover', className)}
      loading="lazy"
    />
  )
}

/**
 * A stamp grid.
 *
 * Wraps at six per row, which is what keeps a ten-stamp card readable at card
 * width. `card-design.ts` refuses to choose this style above twelve stamps.
 */
function Stamps({
  filled,
  total,
  accent,
  foreground,
}: {
  filled: number
  total: number
  accent: string
  foreground: string
}) {
  const cells = Array.from({ length: Math.max(0, total) })
  return (
    <div className="flex flex-wrap gap-1.5" role="img" aria-label={`${filled} / ${total}`}>
      {cells.map((_, index) => {
        const isFilled = index < filled
        return (
          <span
            key={index}
            aria-hidden
            className="size-5 rounded-full border-2 transition-colors duration-300"
            style={{
              borderColor: isFilled ? accent : `${foreground}59`,
              backgroundColor: isFilled ? accent : 'transparent',
            }}
          />
        )
      })}
    </div>
  )
}

function ProgressBar({
  ratio,
  accent,
  track,
  label,
}: {
  ratio: number
  accent: string
  track: string
  label: string
}) {
  return (
    <div
      className="h-2 overflow-hidden rounded-full"
      style={{ backgroundColor: track }}
      role="progressbar"
      aria-valuenow={Math.round(ratio * 100)}
      aria-valuemin={0}
      aria-valuemax={100}
      aria-label={label}
    >
      <div
        className="h-full rounded-full transition-[width] duration-700 ease-out motion-reduce:transition-none"
        style={{ width: `${ratio * 100}%`, backgroundColor: accent }}
      />
    </div>
  )
}

/**
 * A deterministic QR-looking pattern.
 *
 * Not a real QR code: a preview has nothing to encode, and a scannable code that
 * resolves to nothing is worse than an obvious placeholder. Seeded rather than
 * random so the server and client render identical markup — `Math.random()` here
 * is a hydration mismatch on every load.
 */
function QrPattern({ className, dark = '#111827' }: { className?: string; dark?: string }) {
  const cells = React.useMemo(() => {
    const size = 21
    const grid: boolean[] = []
    let state = 0x2f6e2b1
    for (let index = 0; index < size * size; index += 1) {
      state = (state * 1103515245 + 12345) & 0x7fffffff
      grid.push(((state >> 16) & 1) === 1)
    }
    const finder = (row: number, col: number) => {
      for (let r = 0; r < 7; r += 1) {
        for (let c = 0; c < 7; c += 1) {
          const edge = r === 0 || r === 6 || c === 0 || c === 6
          const core = r >= 2 && r <= 4 && c >= 2 && c <= 4
          grid[(row + r) * size + (col + c)] = edge || core
        }
      }
    }
    finder(0, 0)
    finder(0, size - 7)
    finder(size - 7, 0)
    return grid
  }, [])

  return (
    <div
      aria-hidden
      className={cn('grid', className)}
      style={{ gridTemplateColumns: 'repeat(21, minmax(0, 1fr))' }}
    >
      {cells.map((filled, index) => (
        <span key={index} style={{ backgroundColor: filled ? dark : 'transparent' }} />
      ))}
    </div>
  )
}

/** A labelled field, the unit Apple lays a pass out in. */
function Field({
  label,
  children,
  align = 'left',
  labelColor,
  className,
}: {
  label: string
  children: React.ReactNode
  align?: 'left' | 'right'
  labelColor: string
  className?: string
}) {
  return (
    <div className={cn('min-w-0', align === 'right' && 'text-right', className)}>
      <p
        className="truncate text-[9px] font-semibold uppercase tracking-[0.14em]"
        style={{ color: labelColor }}
      >
        {label}
      </p>
      <div className="mt-0.5 truncate text-sm font-medium">{children}</div>
    </div>
  )
}

// -----------------------------------------------------------------------------
// Apple
// -----------------------------------------------------------------------------

export function ApplePassPreview({
  design,
  data,
  showBack = false,
  animateKey,
  className,
}: Omit<CardPreviewProps, 'platform'>) {
  const { t, formatNumber } = useI18n()
  const { rewardReady, remaining, ratio } = useProgress(data)

  const fg = design.foregroundColor
  const label = `${fg}b3`
  const surface = cardBackground(design)

  if (showBack) {
    return <CardBack design={design} data={data} className={className} platform="apple" />
  }

  return (
    <div
      className={cn(
        'relative w-full max-w-[340px] overflow-hidden rounded-[1.25rem] shadow-2xl ring-1 ring-black/10',
        className
      )}
      style={{ background: surface, color: fg, fontFamily: fontStack(design.typography) }}
    >
      {/* Apple's passes carry a soft top light; without it a flat hex reads as a div. */}
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0 bg-gradient-to-b from-white/12 via-transparent to-black/20"
      />

      <div className="relative p-4">
        {/* Header row — logo, logoText, one header field. */}
        <header className="flex items-center gap-2.5">
          <LogoMark
            design={design}
            name={data.organizationName}
            className="size-8 shrink-0 rounded-lg text-[11px]"
            style={{ backgroundColor: design.logoUrl ? 'transparent' : `${fg}26`, color: fg }}
          />
          <p className="min-w-0 flex-1 truncate text-[13px] font-semibold">
            {design.headline ?? data.organizationName}
          </p>
          {design.showTier && data.tierName && (
            <Field label={t('wallet.preview.tier')} align="right" labelColor={label}>
              {data.tierName}
            </Field>
          )}
        </header>

        {/* Apple places `strip.png` directly beneath the header. */}
        {design.heroImageUrl && (
          <HeroStrip url={design.heroImageUrl} className="mt-3 rounded-lg" />
        )}

        {/* Primary field — the number the customer opens the card to see. */}
        {design.showProgress && design.effectiveProgress !== 'none' && (
          <div className="mt-5">
            <p
              className="text-[9px] font-semibold uppercase tracking-[0.14em]"
              style={{ color: label }}
            >
              {data.unitPlural}
            </p>

            {design.effectiveProgress === 'stamps' && data.goal ? (
              <div className="mt-2">
                <Stamps
                  filled={data.balance}
                  total={data.goal}
                  accent={design.accentColor}
                  foreground={fg}
                />
              </div>
            ) : (
              <p
                key={animateKey}
                className="mt-0.5 text-[2.6rem] font-bold leading-none tabular-nums motion-safe:animate-in motion-safe:zoom-in-95 motion-safe:duration-300"
              >
                {formatNumber(data.balance)}
                {data.goal != null && data.goal > 0 && design.effectiveProgress !== 'points' && (
                  <span className="text-xl font-medium" style={{ color: label }}>
                    {' / '}
                    {formatNumber(data.goal)}
                  </span>
                )}
              </p>
            )}

            {design.effectiveProgress === 'bar' && data.goal != null && data.goal > 0 && (
              <div className="mt-3">
                <ProgressBar
                  ratio={ratio}
                  accent={design.accentColor}
                  track={`${fg}2e`}
                  label={data.unitPlural}
                />
              </div>
            )}
          </div>
        )}

        {/* Secondary field — the reward. */}
        {design.showReward && (
          <div className="mt-5">
            <p
              className="flex items-center gap-1 text-[9px] font-semibold uppercase tracking-[0.14em]"
              style={{ color: rewardReady ? design.accentColor : label }}
            >
              {rewardReady && <Sparkles className="size-3" aria-hidden />}
              {rewardReady ? t('card.rewardReady') : t('wallet.preview.reward')}
            </p>
            <p className="mt-0.5 text-sm font-medium leading-snug">
              {data.rewardName ?? t('wallet.preview.reward')}
            </p>
            {!rewardReady && remaining !== null && remaining > 0 && (
              <p className="mt-0.5 text-[11px]" style={{ color: label }}>
                {t('card.toGo', { count: remaining })}
              </p>
            )}
          </div>
        )}

        {/* Auxiliary fields. */}
        {(design.showMemberName || design.showMemberSince || design.showLocation) && (
          <div className="mt-5 flex items-end justify-between gap-3">
            <div className="min-w-0 space-y-1">
              {design.showMemberName && data.memberName && (
                <Field label={t('wallet.preview.member')} labelColor={label}>
                  {data.memberName}
                </Field>
              )}
              {design.showLocation && data.locationName && (
                <p className="flex items-center gap-1 truncate text-[11px]" style={{ color: label }}>
                  <MapPin className="size-3 shrink-0" aria-hidden />
                  {data.locationName}
                </p>
              )}
            </div>
            {design.showMemberSince && data.memberSince && (
              <Field label={t('wallet.preview.memberSince')} align="right" labelColor={label}>
                {data.memberSince}
              </Field>
            )}
          </div>
        )}
      </div>

      {/* The barcode well. Apple renders it on white regardless of the pass
          colour, because scanners need the contrast. */}
      <div className="relative px-4 pb-4">
        <div className="flex flex-col items-center gap-1.5 rounded-xl bg-white p-3">
          <QrPattern className="size-24" />
          <p className="text-[9px] font-medium tracking-wide text-neutral-500">
            {t('wallet.preview.showQr')}
          </p>
        </div>
      </div>
    </div>
  )
}

// -----------------------------------------------------------------------------
// Google
// -----------------------------------------------------------------------------

export function GooglePassPreview({
  design,
  data,
  showBack = false,
  animateKey,
  className,
}: Omit<CardPreviewProps, 'platform'>) {
  const { t, formatNumber } = useI18n()
  const { rewardReady, remaining, ratio } = useProgress(data)

  if (showBack) {
    return <CardBack design={design} data={data} className={className} platform="google" />
  }

  const headerBg = design.backgroundColor
  const headerFg = design.foregroundColor

  return (
    <div
      className={cn(
        // Google's card is a neutral sheet with a branded header, not a
        // fully-branded surface. Getting this wrong is the most common way a
        // "Google Wallet preview" turns out to be an Apple pass in disguise.
        'relative w-full max-w-[340px] overflow-hidden rounded-2xl bg-white text-neutral-900 shadow-2xl ring-1 ring-black/10 dark:bg-neutral-900 dark:text-neutral-100',
        className
      )}
      style={{ fontFamily: fontStack(design.typography) }}
    >
      <div className="px-4 py-3.5" style={{ backgroundColor: headerBg, color: headerFg }}>
        <div className="flex items-center gap-2.5">
          <LogoMark
            design={design}
            name={data.organizationName}
            className="size-9 shrink-0 rounded-full text-[11px]"
            style={{
              backgroundColor: design.logoUrl ? '#ffffff' : `${headerFg}26`,
              color: headerFg,
            }}
          />
          <div className="min-w-0 flex-1">
            <p className="truncate text-[13px] font-semibold leading-tight">
              {design.headline ?? data.organizationName}
            </p>
            <p className="truncate text-[11px] opacity-75">{data.programName}</p>
          </div>
        </div>
      </div>

      {/* Google places `heroImage` full-bleed under the branded header. */}
      {design.heroImageUrl && <HeroStrip url={design.heroImageUrl} />}

      <div className="space-y-4 p-4">
        {design.showProgress && design.effectiveProgress !== 'none' && (
          <div>
            <p className="text-[10px] font-medium uppercase tracking-wider text-neutral-500 dark:text-neutral-400">
              {data.unitPlural}
            </p>

            {design.effectiveProgress === 'stamps' && data.goal ? (
              <div className="mt-2">
                <Stamps
                  filled={data.balance}
                  total={data.goal}
                  accent={design.accentColor}
                  foreground="#71717a"
                />
              </div>
            ) : (
              <p
                key={animateKey}
                className="mt-0.5 text-3xl font-semibold leading-none tabular-nums motion-safe:animate-in motion-safe:zoom-in-95 motion-safe:duration-300"
              >
                {formatNumber(data.balance)}
                {data.goal != null && data.goal > 0 && design.effectiveProgress !== 'points' && (
                  <span className="text-base font-normal text-neutral-500 dark:text-neutral-400">
                    {' / '}
                    {formatNumber(data.goal)}
                  </span>
                )}
              </p>
            )}

            {design.effectiveProgress === 'bar' && data.goal != null && data.goal > 0 && (
              <div className="mt-3">
                <ProgressBar
                  ratio={ratio}
                  accent={design.accentColor}
                  track="#e4e4e7"
                  label={data.unitPlural}
                />
              </div>
            )}
          </div>
        )}

        {design.showReward && (
          <div
            className="rounded-xl p-3"
            style={{ backgroundColor: `${design.accentColor}1f` }}
          >
            <p className="flex items-center gap-1 text-[10px] font-medium uppercase tracking-wider text-neutral-600 dark:text-neutral-300">
              {rewardReady && <Sparkles className="size-3" aria-hidden />}
              {rewardReady ? t('card.rewardReady') : t('wallet.preview.reward')}
            </p>
            <p className="mt-1 text-sm font-medium">{data.rewardName ?? t('wallet.preview.reward')}</p>
            {!rewardReady && remaining !== null && remaining > 0 && (
              <p className="mt-0.5 text-[11px] text-neutral-600 dark:text-neutral-400">
                {t('card.toGo', { count: remaining })}
              </p>
            )}
          </div>
        )}

        <dl className="grid grid-cols-2 gap-3 text-[11px]">
          {design.showMemberName && data.memberName && (
            <div className="min-w-0">
              <dt className="text-neutral-500 dark:text-neutral-400">{t('wallet.preview.member')}</dt>
              <dd className="truncate font-medium">{data.memberName}</dd>
            </div>
          )}
          {design.showTier && data.tierName && (
            <div className="min-w-0">
              <dt className="text-neutral-500 dark:text-neutral-400">{t('wallet.preview.tier')}</dt>
              <dd className="truncate font-medium">{data.tierName}</dd>
            </div>
          )}
          {design.showMemberSince && data.memberSince && (
            <div className="min-w-0">
              <dt className="text-neutral-500 dark:text-neutral-400">
                {t('wallet.preview.memberSince')}
              </dt>
              <dd className="truncate font-medium">{data.memberSince}</dd>
            </div>
          )}
          {design.showLocation && data.locationName && (
            <div className="min-w-0">
              <dt className="text-neutral-500 dark:text-neutral-400">{t('locations.title')}</dt>
              <dd className="truncate font-medium">{data.locationName}</dd>
            </div>
          )}
        </dl>
      </div>

      <div className="border-t border-neutral-200 p-4 dark:border-neutral-800">
        <div className="flex flex-col items-center gap-1.5 rounded-xl bg-white p-3 ring-1 ring-neutral-200">
          <QrPattern className="size-24" />
          <p className="text-[9px] font-medium tracking-wide text-neutral-500">
            {t('wallet.preview.showQr')}
          </p>
        </div>
      </div>
    </div>
  )
}

// -----------------------------------------------------------------------------
// The back of the card
// -----------------------------------------------------------------------------

/**
 * The reverse — where both wallets put contact details and small print.
 *
 * Worth previewing because it is the only place a merchant's own words reach the
 * customer unprompted, and the only place the brand kit's contact fields surface
 * on the card at all.
 */
function CardBack({
  design,
  data,
  platform,
  className,
}: {
  design: ResolvedCardDesign
  data: CardPreviewData
  platform: 'apple' | 'google'
  className?: string
}) {
  const { t } = useI18n()
  const isApple = platform === 'apple'
  const contact = data.contact ?? {}

  const rows = [
    { label: t('brandKit.website'), value: contact.website },
    { label: t('brandKit.phone'), value: contact.phone },
    { label: t('brandKit.email'), value: contact.email },
    { label: t('brandKit.address'), value: contact.address },
  ].filter((row): row is { label: string; value: string } => Boolean(row.value))

  const socials = [
    contact.socials?.instagram,
    contact.socials?.facebook,
    contact.socials?.tiktok,
  ].filter((handle): handle is string => Boolean(handle))

  /*
   * "Empty" means the merchant has given the back nothing of their own. The
   * business name alone does not count — it is on the front too, so a back
   * showing only that is the state the hint is meant to prompt them out of.
   */
  const isEmpty =
    !design.customMessage &&
    !design.termsText &&
    !contact.description &&
    rows.length === 0 &&
    socials.length === 0

  return (
    <div
      className={cn(
        'w-full max-w-[340px] overflow-hidden rounded-[1.25rem] shadow-2xl ring-1 ring-black/10',
        isApple ? '' : 'bg-white dark:bg-neutral-900',
        className
      )}
      style={
        isApple
          ? {
              background: shift(design.backgroundColor, -0.15),
              color: design.foregroundColor,
              fontFamily: fontStack(design.typography),
            }
          : { fontFamily: fontStack(design.typography) }
      }
    >
      <div className="space-y-4 p-4 text-[12px] leading-relaxed">
        <p className="text-[10px] font-semibold uppercase tracking-[0.14em] opacity-60">
          {t('cardDesign.back.title')}
        </p>

        {design.customMessage && <p className="font-medium">{design.customMessage}</p>}

        <div className="space-y-1.5 opacity-80">
          <p className="font-semibold">{data.organizationName}</p>
          {contact.description && <p className="opacity-80">{contact.description}</p>}

          {/* Contact rows. Plain text rather than links: this is a picture of a
              pass, and a live `tel:` here would dial the merchant's own phone
              from the merchant's own dashboard the first time they tapped it. */}
          <dl className="space-y-1 pt-1">
            {rows.map((row) => (
              <div key={row.label} className="flex gap-2">
                <dt className="shrink-0 opacity-60">{row.label}</dt>
                <dd className="min-w-0 flex-1 truncate">{row.value}</dd>
              </div>
            ))}
          </dl>

          {socials.length > 0 && (
            <p className="flex flex-wrap gap-x-3 gap-y-1 pt-1 opacity-70">
              {socials.map((social) => (
                <span key={social}>@{social}</span>
              ))}
            </p>
          )}
        </div>

        {design.termsText && (
          <div className="border-t border-current/15 pt-3">
            <p className="text-[10px] opacity-60">{design.termsText}</p>
          </div>
        )}

        {isEmpty && <p className="opacity-60">{t('cardDesign.back.empty')}</p>}
      </div>
    </div>
  )
}
